---
- hosts: all
  tasks:
    - name: Send notification message via {{ inventory_hostname }}
      mattermost:
        url: "http://mattermost.pichuang.local"
        api_key: "{{ api_key }}"
        channel: "{{ channel }}"
        username: "bot"
        text: "{{ message }}"
        validate_certs: no
